official-repo: &official-repo
  DanySK/Curriculum-Vitae
dist: bionic
language: bash
git:
  depth: false
addons:
  apt:
    update: true
    packages:
    # LaTeX decent font processor
    - cm-super
    # For Minted
    - python-pygments
    # LaTeX
    - texlive-base
    - texlive-science
    - texlive-publishers
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-fonts-recommended
    # Italian
    - texlive-lang-italian
    # Debug
    - tree
env:
  global:
    - TERM="dumb"
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
install:
  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - sdk install kscript
script:
  - ./build.kts
after_failure:
  - tree -a
  - cat *.log
before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ "$(git tag --points-at HEAD)" == "" ]]; then git tag $(./filterDate.kts $(git show -s --format=%ci HEAD)) || :; fi
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: releases
    api_key:
      secure: iYJORfIWamPp7PlC1k233OodHK+oBF8zU4hIncDARa1vhRNi7ikPNklvOa/bXCt1rvoZIfp5oE1EfGSwpnl648H74hevtccotpEnQPVOoGg8kYgp9szfZv847ooza/+WG0dz4lsPWaduwSOdtN24GWS30uMzOCt2LgNG5adX5bO8Pet3lwCLTRBAD+bFKSXjVo+LApgvN38f8FPB7kRK4Np4hZV+bsrzUQqQ7r8K139scqJV3mWHG1T4mwXdhASl165u6AnwweD5rgus0OgojlrA8vbQ/6dSBPTRGprN6s8s5V4ewmcaMbfF/svHvURRlwZDdM+UH1kyCUK/qEowoBZGQDXFQP6gLId2CorH8/E01I/sfzL9zekthnD+Eb9U5co/lxpjec1V1xUjIL3WuXk5Pi+wmOaueoGtwNqx7rf+iyTWNrUUdJMePVlqLTRuavDfYKQQSWdY/cusX2pGJtKRkuOykjfTrsgz0CZ24wi7u8bekvDjtjjFesq+Ru8WcT3hqFTJOonQoRitk5Ki3LU1uK0tMg06qh98pN0dJJZopovMx+Zj4cPspl2QLc62boLKwKui3nRVdbMbpth7KUrFm9zHjVbQF/P7iEuEaiXEH0IXSpLlnnfSjRRME+dQssw2H9J53Elz9DchknbIIFVAQ5CjSgAbEuSsaVsWVw4=
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: true
  - provider: releases
    api_key:
      secure: iYJORfIWamPp7PlC1k233OodHK+oBF8zU4hIncDARa1vhRNi7ikPNklvOa/bXCt1rvoZIfp5oE1EfGSwpnl648H74hevtccotpEnQPVOoGg8kYgp9szfZv847ooza/+WG0dz4lsPWaduwSOdtN24GWS30uMzOCt2LgNG5adX5bO8Pet3lwCLTRBAD+bFKSXjVo+LApgvN38f8FPB7kRK4Np4hZV+bsrzUQqQ7r8K139scqJV3mWHG1T4mwXdhASl165u6AnwweD5rgus0OgojlrA8vbQ/6dSBPTRGprN6s8s5V4ewmcaMbfF/svHvURRlwZDdM+UH1kyCUK/qEowoBZGQDXFQP6gLId2CorH8/E01I/sfzL9zekthnD+Eb9U5co/lxpjec1V1xUjIL3WuXk5Pi+wmOaueoGtwNqx7rf+iyTWNrUUdJMePVlqLTRuavDfYKQQSWdY/cusX2pGJtKRkuOykjfTrsgz0CZ24wi7u8bekvDjtjjFesq+Ru8WcT3hqFTJOonQoRitk5Ki3LU1uK0tMg06qh98pN0dJJZopovMx+Zj4cPspl2QLc62boLKwKui3nRVdbMbpth7KUrFm9zHjVbQF/P7iEuEaiXEH0IXSpLlnnfSjRRME+dQssw2H9J53Elz9DchknbIIFVAQ5CjSgAbEuSsaVsWVw4=
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: false
